---
title: "YouTube Analytics"
author: "Sumedh Telang"
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(treemap)
library(reshape2)
library(magrittr)
library(tidyverse)
library(lubridate)
library(packcircles)
library(viridis)

FRVideos <- read.csv('/Users/sumedhtelang/Downloads/Youtube/FRvideos.csv')
GBVideos <- read.csv('/Users/sumedhtelang/Downloads/Youtube/GBvideos.csv')
INVideos <- read.csv('/Users/sumedhtelang/Downloads/Youtube/INvideos.csv')
KRVideos <- read.csv('/Users/sumedhtelang/Downloads/Youtube/KRvideos.csv')
CAVideos <- read.csv('/Users/sumedhtelang/Downloads/Youtube/CAvideos.csv')
USVideos <- read.csv('/Users/sumedhtelang/Downloads/Youtube/USvideos.csv')
```

```{r}
#Data Preprocessing
#Worldwide
##Canada
CA_views<-select(CAVideos,views)
colnames(CA_views)<-c("Canada")
CA_melt<-melt(CA_views)
names(CA_melt)[names(CA_melt) == "value"] <- "views"
names(CA_melt)[names(CA_melt) == "variable"] <- "country"

CA_category<-select(CAVideos,category_id)
colnames(CA_category)<-c("Canada")
CA_melt_category<-melt(CA_category)
```


```{r}
names(CA_melt_category)[names(CA_melt_category) == "value"] <- "category_id"

CA_channel_title <- select(CAVideos,channel_title)
colnames(CA_channel_title)<-c("channel")
CA_melt_channel<-melt(CA_channel_title)
names(CA_melt_channel)[names(CA_melt_channel) == "value"] <- "channel_title"
CA_channel_title <- select(CAVideos,channel_title)

CA_title <- select(CAVideos,title)
colnames(CA_title)<-c("title")
CA_melt_title<-melt(CA_title)
names(CA_melt_title)[names(CA_melt_title) == "value"] <- "title"

CA_likes <- select(CAVideos,likes)
colnames(CA_likes)<-c("likes")
CA_melt_likes<-melt(CA_likes)
names(CA_melt_likes)[names(CA_melt_likes) == "value"] <- "likes"

CA_dislikes <- select(CAVideos,dislikes)
colnames(CA_dislikes)<-c("dislikes")
CA_melt_dislikes<-melt(CA_dislikes)
names(CA_melt_dislikes)[names(CA_melt_dislikes) == "value"] <- "dislikes"

CA_combine <- cbind(CA_melt, CA_melt_category, CA_melt_channel, CA_melt_title, CA_melt_likes, CA_melt_dislikes)
CA_combine$variable <- NULL
CA_combine$variable <- NULL
CA_combine$variable <- NULL
##Canada

##USA
US_views<-select(USVideos,views)
colnames(US_views)<-c("US")
US_melt<-melt(US_views)
names(US_melt)[names(US_melt) == "value"] <- "views"
names(US_melt)[names(US_melt) == "variable"] <- "country"

US_category<-select(USVideos,category_id)
colnames(US_category)<-c("US")
US_melt_category<-melt(US_category)
names(US_melt_category)[names(US_melt_category) == "value"] <- "category_id"

US_channel_title <- select(USVideos,channel_title)
colnames(US_channel_title)<-c("channel")
US_melt_channel<-melt(US_channel_title)
names(US_melt_channel)[names(US_melt_channel) == "value"] <- "channel_title"
US_channel_title <- select(USVideos,channel_title)

US_title <- select(USVideos,title)
colnames(US_title)<-c("title")
US_melt_title<-melt(US_title)
names(US_melt_title)[names(US_melt_title) == "value"] <- "title"

US_likes <- select(USVideos,likes)
colnames(US_likes)<-c("likes")
US_melt_likes<-melt(US_likes)
names(US_melt_likes)[names(US_melt_likes) == "value"] <- "likes"

US_dislikes <- select(USVideos,dislikes)
colnames(US_dislikes)<-c("dislikes")
US_melt_dislikes<-melt(US_dislikes)
names(US_melt_dislikes)[names(US_melt_dislikes) == "value"] <- "dislikes"

US_combine <- cbind(US_melt, US_melt_category, US_melt_channel, US_melt_title, US_melt_likes, US_melt_dislikes)
US_combine$variable <- NULL
US_combine$variable <- NULL
US_combine$variable <- NULL
##USA

##INDIA
IN_views<-select(INVideos,views)
colnames(IN_views)<-c("India")
IN_melt<-melt(IN_views)
names(IN_melt)[names(IN_melt) == "value"] <- "views"
names(IN_melt)[names(IN_melt) == "variable"] <- "country"

IN_category<-select(INVideos,category_id)
colnames(IN_category)<-c("India")
IN_melt_category<-melt(IN_category)
names(IN_melt_category)[names(IN_melt_category) == "value"] <- "category_id"

IN_channel_title <- select(INVideos,channel_title)
colnames(IN_channel_title)<-c("channel")
IN_melt_channel<-melt(IN_channel_title)
names(IN_melt_channel)[names(IN_melt_channel) == "value"] <- "channel_title"
IN_channel_title <- select(INVideos,channel_title)

IN_title <- select(INVideos,title)
colnames(IN_title)<-c("title")
IN_melt_title<-melt(IN_title)
names(IN_melt_title)[names(IN_melt_title) == "value"] <- "title"

IN_likes <- select(INVideos,likes)
colnames(IN_likes)<-c("likes")
IN_melt_likes<-melt(IN_likes)
names(IN_melt_likes)[names(IN_melt_likes) == "value"] <- "likes"

IN_dislikes <- select(INVideos,dislikes)
colnames(IN_dislikes)<-c("dislikes")
IN_melt_dislikes<-melt(IN_dislikes)
names(IN_melt_dislikes)[names(IN_melt_dislikes) == "value"] <- "dislikes"

IN_combine <- cbind(IN_melt, IN_melt_category, IN_melt_channel, IN_melt_title, IN_melt_likes, IN_melt_dislikes)
IN_combine$variable <- NULL
IN_combine$variable <- NULL
IN_combine$variable <- NULL
##INDIA

##GREAT BRITAIN
GB_views<-select(GBVideos,views)
colnames(GB_views)<-c("Great Britain")
GB_melt<-melt(GB_views)
names(GB_melt)[names(GB_melt) == "value"] <- "views"
names(GB_melt)[names(GB_melt) == "variable"] <- "country"

GB_category<-select(GBVideos,category_id)
colnames(GB_category)<-c("Great Britain")
GB_melt_category<-melt(GB_category)
names(GB_melt_category)[names(GB_melt_category) == "value"] <- "category_id"

GB_channel_title <- select(GBVideos,channel_title)
colnames(GB_channel_title)<-c("channel")
GB_melt_channel<-melt(GB_channel_title)
names(GB_melt_channel)[names(GB_melt_channel) == "value"] <- "channel_title"
GB_channel_title <- select(GBVideos,channel_title)

GB_title <- select(GBVideos,title)
colnames(GB_title)<-c("title")
GB_melt_title<-melt(GB_title)
names(GB_melt_title)[names(GB_melt_title) == "value"] <- "title"

GB_likes <- select(GBVideos,likes)
colnames(GB_likes)<-c("likes")
GB_melt_likes<-melt(GB_likes)
names(GB_melt_likes)[names(GB_melt_likes) == "value"] <- "likes"

GB_dislikes <- select(GBVideos,dislikes)
colnames(GB_dislikes)<-c("dislikes")
GB_melt_dislikes<-melt(GB_dislikes)
names(GB_melt_dislikes)[names(GB_melt_dislikes) == "value"] <- "dislikes"

GB_combine <- cbind(GB_melt, GB_melt_category, GB_melt_channel, GB_melt_title, GB_melt_likes, GB_melt_dislikes)
GB_combine$variable <- NULL
GB_combine$variable <- NULL
GB_combine$variable <- NULL
##GREAT BRITAIN

##FRANCE
FR_views<-select(FRVideos,views)
colnames(FR_views)<-c("France")
FR_melt<-melt(FR_views)
names(FR_melt)[names(FR_melt) == "value"] <- "views"
names(FR_melt)[names(FR_melt) == "variable"] <- "country"

FR_category<-select(FRVideos,category_id)
colnames(FR_category)<-c("France")
FR_melt_category<-melt(FR_category)
names(FR_melt_category)[names(FR_melt_category) == "value"] <- "category_id"

FR_channel_title <- select(FRVideos,channel_title)
colnames(FR_channel_title)<-c("channel")
FR_melt_channel<-melt(FR_channel_title)
names(FR_melt_channel)[names(FR_melt_channel) == "value"] <- "channel_title"
FR_channel_title <- select(FRVideos,channel_title)

FR_title <- select(FRVideos,title)
colnames(FR_title)<-c("title")
FR_melt_title<-melt(FR_title)
names(FR_melt_title)[names(FR_melt_title) == "value"] <- "title"

FR_likes <- select(FRVideos,likes)
colnames(FR_likes)<-c("likes")
FR_melt_likes<-melt(FR_likes)
names(FR_melt_likes)[names(FR_melt_likes) == "value"] <- "likes"

FR_dislikes <- select(FRVideos,dislikes)
colnames(FR_dislikes)<-c("dislikes")
FR_melt_dislikes<-melt(FR_dislikes)
names(FR_melt_dislikes)[names(FR_melt_dislikes) == "value"] <- "dislikes"

FR_combine <- cbind(FR_melt, FR_melt_category, FR_melt_channel, FR_melt_title, FR_melt_likes, FR_melt_dislikes)
FR_combine$variable <- NULL
FR_combine$variable <- NULL
FR_combine$variable <- NULL
##FRANCE

##KOREA
KR_views<-select(KRVideos,views)
colnames(KR_views)<-c("Korea")
KR_melt<-melt(KR_views)
names(KR_melt)[names(KR_melt) == "value"] <- "views"
names(KR_melt)[names(KR_melt) == "variable"] <- "country"

KR_category<-select(KRVideos,category_id)
colnames(KR_category)<-c("Korea")
KR_melt_category<-melt(KR_category)
names(KR_melt_category)[names(KR_melt_category) == "value"] <- "category_id"

KR_channel_title <- select(KRVideos,channel_title)
colnames(KR_channel_title)<-c("channel")
KR_melt_channel<-melt(KR_channel_title)
names(KR_melt_channel)[names(KR_melt_channel) == "value"] <- "channel_title"
KR_channel_title <- select(KRVideos,channel_title)

KR_title <- select(KRVideos,title)
colnames(KR_title)<-c("title")
KR_melt_title<-melt(KR_title)
names(KR_melt_title)[names(KR_melt_title) == "value"] <- "title"

KR_likes <- select(KRVideos,likes)
colnames(KR_likes)<-c("likes")
KR_melt_likes<-melt(KR_likes)
names(KR_melt_likes)[names(KR_melt_likes) == "value"] <- "likes"

KR_dislikes <- select(KRVideos,dislikes)
colnames(KR_dislikes)<-c("dislikes")
KR_melt_dislikes<-melt(KR_dislikes)
names(KR_melt_dislikes)[names(KR_melt_dislikes) == "value"] <- "dislikes"

KR_combine <- cbind(KR_melt, KR_melt_category, KR_melt_channel, KR_melt_title, KR_melt_likes, KR_melt_dislikes)
KR_combine$variable <- NULL
KR_combine$variable <- NULL
KR_combine$variable <- NULL
##KOREA
```
```{r}
#Final DataFrame for Worldwide Visualizations
Complete<-rbind(CA_combine, US_combine, IN_combine, GB_combine, FR_combine, KR_combine)

Complete = Complete %>% mutate(category_id = case_when(
  category_id== '1' ~ 'Film and Animation',
  category_id== '2' ~ 'Autos and Vehicles',
  category_id== '10'~ 'Music',
  category_id== '15'~ 'Pets and Animals',
  category_id== '17'~ 'Sports',
  category_id== '18'~ 'Short Movies',
  category_id== '19'~ 'Travel and Events',
  category_id== '20'~'Gaming',
  category_id== '21'~'Videoblogging',
  category_id== '22'~ 'People and Blogs',
  category_id== '23'~ 'Comedy',
  category_id== '24'~ 'Entertainment',
  category_id== '25'~ 'News and Politics',
  category_id== '26'~ 'How to and Style',
  category_id== '27'~ 'Education',
  category_id== '28'~ 'Science and Technology',
  category_id== '29'~ 'Nonprofits & Activism',
  category_id== '30'~ 'Movies',
  category_id== '31'~ 'Anime/Animation',
  category_id== '32'~ 'Action/Adventure',
  category_id== '33'~ 'Classics',
  category_id== '34'~ 'Comedy',
  category_id== '35'~ 'Documentary',
  category_id== '36'~ 'Drama',
  category_id== '37'~ 'Family',
  category_id== '38'~ 'Foreign',
  category_id== '39'~ 'Horror',
  category_id== '40'~ 'Sci-Fi/Fantasy',
  category_id== '41'~ 'Thriller',
  category_id== '42'~ 'Shorts',
  category_id== '43'~ 'Shows',
  category_id== '44'~ 'Trailers'))

```

```{r}
#Top 10 popular Genres in World
World_Top10_Popular_Categories = Complete %>% count(category_id)%>% 
  arrange(desc(n))%>% head(10)%>%rename("No.of.Videos" = n)

ggplot(World_Top10_Popular_Categories,aes(category_id,No.of.Videos))+
  geom_bar(stat = "identity",aes(fill=category_id))+theme(text = element_text(size=10),
                                                       axis.text.x = element_text(angle=90, hjust=1))

```

```{r}
#Top 10 channels Worldwide
World_Top10_Channels_with_most_trending_videos = Complete %>% count(channel)%>% 
  arrange(desc(n))%>% head(10)%>%rename("No.of.Videos" = n)

labels = c("Jimmy Kimmel","Seth Meyers","Netflix","RadaanMedia","James Corden","Stephen Colbert","Jimmy Fallon","Ellen Show","VikatanTV","WWE")

ggplot(World_Top10_Channels_with_most_trending_videos,aes(channel,No.of.Videos))+
  geom_bar(stat = "identity",aes(fill = channel ))+scale_x_discrete(labels = labels)+theme(text = element_text(size=10),
                                                                                                 axis.text.x = element_text(angle=90, hjust=1))

```

```{r}
# Top 10 Videos trending for a longer period Worldwide
World_Top10_Longest_trending_videos = Complete %>% count(title)%>% 
  arrange(desc(n))%>% head(10)%>% rename("days_trending" = n)

labels1 = c("Ariana Grande - No Tears Left To Cry", "This is America", "Ed Sheeran - Happier","Incredibles 2 Sneak peek","Incredibles 2 Trailer","Maroon 5 - Wait","Antman and The Wasp","Mission Impossible : Fallout","Sam Smith - Pray","Taylor Swift - Delicate")


ggplot(World_Top10_Longest_trending_videos,aes(title,days_trending))+
  geom_bar(stat = "identity",aes(fill = title))+scale_x_discrete(labels = labels1)+theme(text = element_text(size=10),
                                                      axis.text.x = element_text(angle=90, hjust=1))


```

```{r}
# Views per Category - Worldwide
ggplot(Complete,aes(category_id,views))+geom_boxplot(fill = "orange",color = "blue")+scale_y_log10()+
  theme(text = element_text(size=10),axis.text.x = element_text(angle=90, hjust=1))

```

```{r}
#Top 10 Most liked videos in World
World_Top10_most_liked_videos = Complete %>% select(title,channel,likes) %>% distinct(title,.keep_all = TRUE) %>%
  mutate(Title = title)%>%arrange(desc(likes))%>% head(10)

World_Top10_most_liked_videos$Title = c("Fake Love official by BTS","MIC Drop by BTS","Daydream by j-hope","Love Yourself by BTS","Avengers:Infinity War Trailer","Perfect by Ed Sheeran","Euphoria by BTS","Fake Love Extended by BTS","Drake God's Plan","Airplane by j-hope")

Map_US_most_liked = treemap(World_Top10_most_liked_videos,index = "Title",vSize = "likes",type = "index",title = "Most Liked Videos in World",palette="RdYlBu")

```

```{r}
#Top 10 Most disliked videos in World
World_Top10_most_disliked_videos = Complete %>% select(title,channel,dislikes) %>% distinct(title,.keep_all = TRUE) %>%
  mutate(Title = title)%>%arrange(desc(dislikes))%>% head(10)

World_Top10_most_disliked_videos$Title = c("So sorry","YouTube Rewind 2017","Vittar - Lucas Lucco","Logan  Paul is Back","Jake Paul : Saturday Night Song","Official Call of Duty Black Ops 4","Suicide: Be Here Tomorrow. - Logan Paul","PSA from Chairman of the FCC Ajit Pai","Declaring Voter's Strike","Gucci by Timati")


Map_US_most_disliked = treemap(World_Top10_most_disliked_videos,index = "Title",vSize = "dislikes",type = "index",title = "Most Disliked Videos Worldwide",palette="RdYlBu")

```

```{r}
#Most Interactions based on average number of view per country
Avg<-summarise(group_by(Complete,country),average=mean(views))


packing<-circleProgressiveLayout(Avg$average,sizetype = 'area')
Avg2<-cbind(Avg,packing)
Avg2$group<-c(1,2,3,4,5,6)
dat.gg <- circleLayoutVertices(packing, npoints=50)

ggplot() + 
  geom_polygon(data = dat.gg, aes(x, y, group = id, fill=as.factor(id)), colour = "white", alpha = 0.6) +
  scale_fill_manual(values = inferno(nrow(Avg2))) +
  geom_text(data = Avg2, aes(x, y, size=average, label = country)) +
  scale_size_continuous(range = c(1,4)) +
  theme_void() + 
  theme(legend.position="none") +
  coord_equal()+ggtitle("Country-Views")
```

```{r}
#Avg no. of days for a video to trend in USA
USVideos$publishtime<-lubridate::date(USVideos$publish_time)
Required<-select(USVideos,trending_date,category_id,publishtime)
Required$publish_date<-format(as.Date(Required$publishtime),"%Y-%m-%d")
Required<-Required[,-3]
Required$trending_date<-ydm(Required$trending_date)
Required$trending_date<-ymd(Required$trending_date)
Required$publish_date<-ymd(Required$publish_date)
Required$difference<-as.numeric(difftime(Required$trending_date,Required$publish_date,units = "days"))
Table<-summarise(group_by(Required,category_id),average=mean(difference))
Table<-Table %>%
  mutate(category_name=case_when(
      category_id==1 ~ 'Film and Animation',
      category_id==2 ~ 'Autos & Vehicles',
      category_id==10 ~ 'Music',
      category_id==15 ~ 'Pets & Animals',
      category_id==17 ~ 'Sports',
      category_id==19 ~ 'Travel & Events',
      category_id==20 ~ 'Gaming',
      category_id==22 ~ 'People & Blogs',
      category_id==23 ~ 'Comedy',
      category_id==24 ~ 'Entertainment',
      category_id==25 ~ 'News & Politics',
      category_id==26 ~ 'Howto & Style',
      category_id==27 ~ 'Education',
      category_id==28 ~ 'Science & Technology',
      category_id==29 ~ 'Nonprofits & Activism',
      category_id==30 ~ 'Movies',
      category_id==43 ~ 'Shows'))
R<-Table[order(Table$average),]
Table$Quantity<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)


ggplot(R, aes(x =reorder(category_name,average), y =average, label =category_id)) +
    geom_jitter(aes(size =average, colour = category_id, alpha=.02)) + 
    geom_text(hjust = 1, size = 2) +
    scale_size(range = c(1,15)) +
    theme_bw()+theme(plot.title = element_text(hjust = 0.5))+theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+xlab("Category Name")+ylab("Avg Days")+ggtitle("Avg Days for Video to Trend")
```

```{r}
#US(Publish Time - Views)
RequiredUS<-select(USVideos,category_id,publish_time,views)
RequiredUS<-RequiredUS %>%
  mutate(category_name=case_when(
      category_id==1 ~ 'Film and Animation',
      category_id==2 ~ 'Autos & Vehicles',
      category_id==10 ~ 'Music',
      category_id==15 ~ 'Pets & Animals',
      category_id==17 ~ 'Sports',
      category_id==19 ~ 'Travel & Events',
      category_id==20 ~ 'Gaming',
      category_id==22 ~ 'People & Blogs',
      category_id==23 ~ 'Comedy',
      category_id==24 ~ 'Entertainment',
      category_id==25 ~ 'News & Politics',
      category_id==26 ~ 'Howto & Style',
      category_id==27 ~ 'Education',
      category_id==28 ~ 'Science & Technology',
      category_id==29 ~ 'Nonprofits & Activism',
      category_id==30 ~ 'Movies',
      category_id==43 ~ 'Shows'))
RequiredUS$publishtime<-format(ymd_hms(RequiredUS$publish_time),"%H:%M:%S")
RequiredUS<-RequiredUS[,c(-2,-1)]



RequiredUS$publishtime<-format(strptime(RequiredUS$publishtime,format='%H:%M:%S'),'%H')
RequiredUS$publishtime<-as.character(RequiredUS$publishtime)

TT<-summarise(group_by(RequiredUS,publishtime),avg=mean(views))



ggplot(TT, aes(x =publishtime, y = avg)) +
    coord_polar(theta = "x", start = -.13) +
    geom_bar(stat = "identity", fill = "lightblue", width = .9) +
    geom_hline(yintercept = seq(0, 500, by = 100), color = "grey80", size = 0.3) +
    scale_x_discrete(breaks = c(0:24), expand = c(.002,0)) +ggtitle("Effect of Publish Time on Views")
    theme_bw()+ theme(panel.grid.minor = element_blank())
```

